### PR TITLE
speed up `roc_curve_survival_impl()`

### PR DESCRIPTION
**Pull request by simonpcouch**
Before this PR, I saw:

``` r
bench::mark(
  yardstick:::roc_curve_survival_impl(
    truth = rr_churn_data$surv,
    estimate = rr_churn_data$surv_prob,
    censoring_weights = rr_churn_data$ipcw,
    eval_time = rr_churn_data$times
  )
)
#> # A tibble: 1 × 13
#>   expression    min median itr/s…¹ mem_a…² gc/se…³ n_itr  n_gc total…⁴ result
#>   <list>     <bch:> <bch:>   <dbl> <bch:b>   <dbl> <int> <dbl> <bch:t> <list>
#> 1 <chr [1]>   50.6s  50.6s  0.0198   133GB    13.7     1   694   50.6s <tibble>
#> # … with 3 more variables: memory <list>, time <list>, gc <list>, and
#> #   abbreviated variable names ¹​`itr/sec`, ²​mem_alloc, ³​`gc/sec`, ⁴​total_time
#> # ℹ Use `colnames()` to see all variable names
```

With this PR:

``` r
#> # A tibble: 1 × 13
#>   expression    min median itr/s…¹ mem_a…² gc/se…³ n_itr  n_gc total…⁴ result
#>   <bch:expr> <bch:> <bch:>   <dbl> <bch:b>   <dbl> <int> <dbl> <bch:t> <list>
#> 1 total       7.59s  7.59s   0.132  12.7GB    40.1     1   304   7.59s <tibble>
#> # … with 3 more variables: memory <list>, time <list>, gc <list>, and
#> #   abbreviated variable names ¹​`itr/sec`, ²​mem_alloc, ³​`gc/sec`, ⁴​total_time
#> # ℹ Use `colnames()` to see all variable names
```

@EmilHvitfeldt mentioned there could be a `sort()`ing trick we could use for the `<=` comparison that might drive this down further. :)

### CODE REVIEW

**Comment by simonpcouch** [comment]
Related to #379! Maybe closes.

**Comment by EmilHvitfeldt** [comment]
I hit it with the good old 

```r
new_res <- yardstick:::roc_curve_survival_impl(
  truth = rr_churn_data$surv,
  estimate = rr_churn_data$surv_prob,
  censoring_weights = rr_churn_data$ipcw,
  eval_time = rr_churn_data$times
)

# readr::write_rds(true_res, "~/Desktop/old_res.rds")
old_res <- readr::read_rds("~/Desktop/old_res.rds")

identical(new_res, old_res)
```

and we are still good!

**Comment by EmilHvitfeldt** [comment]
We are now at 

```r
#> # A tibble: 1 × 13
#>   expression     min median itr/s…¹ mem_a…² gc/se…³ n_itr  n_gc total…⁴ result  
#>   <bch:expr> <bch:t> <bch:>   <dbl> <bch:b>   <dbl> <int> <dbl> <bch:t> <list>  
#> 1 total         5.6s   5.6s   0.179  9.51GB    38.0     1   213    5.6s <tibble>
#> # … with 3 more variables: memory <list>, time <list>, gc <list>, and
#> #   abbreviated variable names ¹​`itr/sec`, ²​mem_alloc, ³​`gc/sec`, ⁴​total_time
#> # ℹ Use `colnames()` to see all variable names
```

**Comment by EmilHvitfeldt** [comment]
We are now finally down to an acceptable amount of time to run.

```r
#> # A tibble: 1 × 13
#>   expression     min median itr/s…¹ mem_a…² gc/se…³ n_itr  n_gc total…⁴ result  
#>   <bch:expr> <bch:t> <bch:>   <dbl> <bch:b>   <dbl> <int> <dbl> <bch:t> <list>  
#> 1 total        359ms  359ms    2.79  11.3MB    13.9     2    10   717ms <tibble>
#> # … with 3 more variables: memory <list>, time <list>, gc <list>, and
#> #   abbreviated variable names ¹​`itr/sec`, ²​mem_alloc, ³​`gc/sec`, ⁴​total_time
#> # ℹ Use `colnames()` to see all variable names
```

I'll need to do some more testing to make sure everything is correct. Since we are sorting things, some sums are now slightly different (to be expected) but I want to make sure it is correct

Screen Shot 2023-03-17 at 3 38 36 PM

**Pull request merged**
