### PR TITLE
mase error on insample

### PR DESCRIPTION
**Pull request by alexhallam**

### CODE REVIEW

**Comment by alexhallam** [comment]
Not sure how to handle the insample argument

**Comment by topepo** [comment]
Is this related to an issue?

**Comment by alexhallam** [comment]
Yeah, I don't know how to properly add a new vector argument to the `mase` function. The issue is here #68

**Comment by topepo** [comment]
So you want to compute the metric for different values of `insample`?

**Comment by alexhallam** [comment]
No, the problem is that MASE needs to know what values are insample. It is a necessary part of the calculation.  MASE is the out-of-sample mae over the in sample mae of the seasonal naive forecast. For this calculation to be possible the user has to label what data is `insample`. 
```
mase <- out_mae / in_snaive_mae
```

**Comment by DavisVaughan** [comment]
Ah, I see what you are trying to say. This is more difficult that I intended it to be. I did not read the definition of the metric correctly, and did not see that it used the in sample MAE as the denominator.

This is difficult because `yardstick` generally has no knowledge of the in sample outcome variable. It only gets the out of sample predictions, and the corresponding out of sample outcomes.

I have one suggestion, and I don't particularly love it, but it might be good enough.

`mase(data, truth, estimate, m = 1, mae_train = NULL)`

We could take `truth`, lag it by `m`, calculate `(truth - truth_lag)`, and compute the denominator using that seasonal 1 step naive forecast, rather than using a true in sample MAE. To me, this has the same rationale as using the in sample one.

If the user knew the in sample mae value, and really wanted to use that, they could pass that single numeric value to `mae_train` and that would override the calculation described above.

**Comment by alexhallam** [comment]
Do you think that if `mae_train` is null that a warning should be thrown stating that this is an ad_hoc mase and that a value for `mae_train` is recommended? Or do you think this would be too forceful?

**Comment by DavisVaughan** [comment]
Sounds too forceful since it's the default. I would definitely be clear in the documentation about the difference though!

**Pull request closed without merging**
