### PR TITLE
Correct the `pr_curve()` implementation when duplicates exist

### LINKED ISSUE #93: pr_curve() doesn't seem to generate correct precision and recall values
Hello,

I think the function `pr_curve()` is not working correctly. It generate values for precision and recall; however, when I plot them, they seem to produce a curve that is not a precision-recall curve.

Here is an example:
``` r
library(tidyverse)
library(broom)
library(yardstick)
#> For binary classification, the first factor level is assumed to be the event.
#> Set the global option `yardstick.event_first` to `FALSE` to change this.
#> 
#> Attaching package: 'yardstick'
#> The following object is masked from 'package:broom':
#> 
#>     tidy
#> The following object is masked from 'package:readr':
#> 
#>     spec

glm(am ~ disp, 
    family = binomial,
    data = mtcars
) %>%
  augment() %>%
  pr_curve(truth = factor(am), .fitted) %>%
  ggplot(aes(x = recall, y = precision)) + 
  geom_line()
#> Warning: Removed 1 rows containing missing values (geom_path).
```

<sup>Created on 2019-03-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #93. Below are 3 examples that were incorrect before, but are now working correctly. The main issue had to do with how duplicate probability values were handled.

This also affected how the PR AUC values were computed for each example. They are now computed correctly for each example. For this, its important to have the `1` value rather than an `NA` for the first precision value. Without it, the AUC value for all of these won't actually be 1, as it should be, because the curve won't cover the full precision/recall range.

---

No duplicates (this was correct before and after the change)

| truth | estimate | tp | fp | recall | precision | used |
|-------|----------|----|----|-------:|-----------|------|
| a     | .9       | 1  | 0  | .5 = 1/2    | 1 = 1/(1+0)   | *    |
| a     | .8       | 2  | 0  | 1 = 2/2    | 1 = 2/(2+0)   | *    |
| b     | .4       | 2  | 1  | 1 = 2/2    | .67 = 2/(2+1)   | *    |
| b     | .3       | 2  | 2  | 1 = 2/2    | .5 = 2/(2+2)   | *    |

After: 

``` r
suppressPackageStartupMessages(library(yardstick))
truth <- factor(c("a", "a", "b", "b"))
estimate <- c(.9, .8, .4, .3)
df <- data.frame(truth, estimate)
pr_curve(df, truth, estimate)
#> # A tibble: 5 x 3
#>   .threshold recall precision
#>        <dbl>  <dbl>     <dbl>
#> 1      Inf      0       1    
#> 2        0.9    0.5     1    
#> 3        0.8    1       1    
#> 4        0.4    1       0.667
#> 5        0.3    1       0.5
```

Before:

``` r
suppressPackageStartupMessages(library(yardstick))
truth <- factor(c("a", "a", "b", "b"))
estimate <- c(.9, .8, .4, .3)
df <- data.frame(truth, estimate)
pr_curve(df, truth, estimate)
#> # A tibble: 5 x 3
#>   .threshold recall precision
#>        <dbl>  <dbl>     <dbl>
#> 1      Inf      0      NA    
#> 2        0.9    0.5     1    
#> 3        0.8    1       1    
#> 4        0.4    1       0.667
#> 5        0.3    1       0.5
```

---

Duplicates at the beginning

| truth | estimate | tp | fp |   recall | precision     | used |
|-------|----------|----|----|---------:|---------------|------|
| a     | .9       | 1  | 0  | .5 = 1/2 | 1 = 1/(1+0)   | -    |
| a     | .9       | 2  | 0  | 1 = 2/2  | 1 = 2/(2+0)   | *    |
| b     | .4       | 2  | 1  | 1 = 2/2  | .67 = 2/(2+1) | *    |
| b     | .3       | 2  | 2  | 1 = 2/2  | .5 = 2/(2+2)  | *    |

After: 

``` r
suppressPackageStartupMessages(library(yardstick))
truth <- factor(c("a", "a", "b", "b"))
estimate <- c(.9, .9, .4, .3)
df <- data.frame(truth, estimate)
pr_curve(df, truth, estimate)
#> # A tibble: 4 x 3
#>   .threshold recall precision
#>        <dbl>  <dbl>     <dbl>
#> 1      Inf        0     1    
#> 2        0.9      1     1    
#> 3        0.4      1     0.667
#> 4        0.3      1     0.5
```

Before:

``` r
suppressPackageStartupMessages(library(yardstick))
truth <- factor(c("a", "a", "b", "b"))
estimate <- c(.9, .9, .4, .3)
df <- data.frame(truth, estimate)
pr_curve(df, truth, estimate)
#> # A tibble: 4 x 3
#>   .threshold recall precision
#>        <dbl>  <dbl>     <dbl>
#> 1      Inf      0      NA    
#> 2        0.9    0.5     1    
#> 3        0.4    1       0.667
#> 4        0.3    1       0.5
```

---

Duplicates at the end

| truth | estimate | tp | fp |   recall | precision     | used |
|-------|----------|----|----|---------:|---------------|------|
| a     | .9       | 1  | 0  | .5 = 1/2 | 1 = 1/(1+0)   | *    |
| a     | .8       | 2  | 0  | 1 = 2/2  | 1 = 2/(2+0)   | *    |
| b     | .3       | 2  | 1  | 1 = 2/2  | .67 = 2/(2+1) | -    |
| b     | .3       | 2  | 2  | 1 = 2/2  | .5 = 2/(2+2)  | *    |

After:

``` r
suppressPackageStartupMessages(library(yardstick))
truth <- factor(c("a", "a", "b", "b"))
estimate <- c(.9, .8, .3, .3)
df <- data.frame(truth, estimate)
pr_curve(df, truth, estimate)
#> # A tibble: 4 x 3
#>   .threshold recall precision
#>        <dbl>  <dbl>     <dbl>
#> 1      Inf      0         1  
#> 2        0.9    0.5       1  
#> 3        0.8    1         1  
#> 4        0.3    1         0.5
```

Before:

``` r
suppressPackageStartupMessages(library(yardstick))
truth <- factor(c("a", "a", "b", "b"))
estimate <- c(.9, .8, .3, .3)
df <- data.frame(truth, estimate)
pr_curve(df, truth, estimate)
#> # A tibble: 4 x 3
#>   .threshold recall precision
#>        <dbl>  <dbl>     <dbl>
#> 1      Inf      0      NA    
#> 2        0.9    0.5     1    
#> 3        0.8    1       1    
#> 4        0.3    1       0.667
```

### CODE REVIEW

**Comment by DavisVaughan** [comment]
This known (pathological) example demonstrates fixing a bug with `order_cpp()` not returning the correct order when there are duplicate class probabilities.

| truth | estimate | tp | fp | recall | precision | used |
|-------|----------|----|----|-------|-----------|------|
| a     | .9       | 1  | 0  | .33 = 1/3    | 1 = 1/(1+0)   | -    |
| b     | .9       | 1  | 1  | .33 = 1/3    | .5 = 1/(1+1)   | *    |
| a     | .4       | 2  | 1  | .67 = 2/3    | .67 = 2/(2+1)   | *    |
| a     | .3       | 3  | 1  | 1 = 3/3    | .75 = 3/(3+1)   | *    |

After:

``` r
suppressPackageStartupMessages(library(yardstick))
truth <- factor(c("a", "b", "a", "a"))
estimate <- c(.9, .9, .4, .3)
df <- data.frame(truth, estimate)
pr_curve(df, truth, estimate)
#> # A tibble: 4 x 3
#>   .threshold recall precision
#>        <dbl>  <dbl>     <dbl>
#> 1      Inf    0         1    
#> 2        0.9  0.333     0.5  
#> 3        0.4  0.667     0.667
#> 4        0.3  1         0.75
```

Before:

``` r
suppressPackageStartupMessages(library(yardstick))
truth <- factor(c("a", "b", "a", "a"))
estimate <- c(.9, .9, .4, .3)
df <- data.frame(truth, estimate)
pr_curve(df, truth, estimate)
#> # A tibble: 4 x 3
#>   .threshold recall precision
#>        <dbl>  <dbl>     <dbl>
#> 1      Inf     0           NA
#> 2        0.9   0.25         1
#> 3        0.4   0.75         1
#> 4        0.3   1            1
```

**Comment by DavisVaughan** [comment]
This PR now also implements `average_precision()` as an alternative to `pr_auc()` that does not have the issue of the ambiguity of dealing with the value of `precision` in the `recall == 0` case.

**Comment by DavisVaughan** [comment]
@dariyasydykova at this point, this PR fixes all of the issues with `pr_curve()` except for the original value for precision at the point where `recall == 0` and `fp == 0`. I'm not sure what to do about that point.


It doesn't look like your tweet got any solid advice either:
https://twitter.com/dariyasydykova/status/1106617500811309056

**Comment by fmannhardt** [comment]
Hi, I am using yardstick for evaluating ML models and it seems I got hit by this issue in pr_curve calculation. Any plan when this would get merged and released?

**Comment by DavisVaughan** [comment]
I'll likely make a pass at all the outstanding yardstick issues / PRs after useR (July 9-12), and then release a new version. Things are pretty packed up until then.

**Comment by fmannhardt** [comment]
Thanks. Will use this branch until then.

**Pull request merged**
